config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('home.urls')),
    path('users/',include('users.urls')),
    path('products/',include('products.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/urls.py
from django.urls import path
from .views import landing_page,GetTest

app_name = 'home'
urlpatterns =[
    path('',landing_page,name='landing_page'),
    path('testt/',GetTest.as_view(),name='test')
]

products/urls.py
from django.urls import path 
from .views import ListView, BookListView,BookDetailView,BookCreateView,BookDeleteView


app_name = 'products'
urlpatterns = [
    path('books/',BookListView.as_view(),name='book_list'),
    path('deatail/<int:pk>',BookDetailView.as_view(),name='book_detail'),
    path('create/',BookCreateView.as_view(),name='book_create'),
    path('delete/<int:pk>',BookDeleteView.as_view(),name='book_delete'),

]

users/urls.py
from django.urls import path
from .views import RegisterView, LoginView, LogoutView

app_name = 'users'
urlpatterns = [
    path('register/', RegisterView.as_view(), name='register'),
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
]

home/models.py
from django.db import models

#Create your models here.

products/models.py
from django.db import models
from users.models import CustomUser
from django.core.validators import MaxValueValidator, MinValueValidator 
# Create your models here.

class CategoryBook(models.Model):
    name=models.CharField(max_length=100)

    class Meta:
        db_table = 'category_book'

    def __str__(self):
        return self.name
    
class LanguageBook(models.Model):
    name=models.CharField(max_length=100)

    class Meta:
        db_table = 'language_book'

    def __str__(self):
        return self.name


class Book(models.Model):
    title=models.CharField(max_length=100)
    price=models.IntegerField()
    description=models.TextField()
    image=models.ImageField(upload_to='books/',default='default_images/book_image.png', blank=True,null=True)
    category=models.ForeignKey(CategoryBook,on_delete=models.CASCADE)
    page=models.IntegerField() 
    book_lang=models.ForeignKey(LanguageBook, on_delete=models.DO_NOTHING)

    created_at=models.DateField(auto_now_add=True)
    updated_at=models.DateField(auto_now=True)

    class Meta:
        db_table = 'book'

    def __str__(self):
        return self.title


class Author(models.Model):
    first_name=models.CharField(max_length=100)
    last_name=models.CharField(max_length=100)

    class Meta:
        db_table = 'author'

    def __str__(self):
        return f'{self.first_name} {self.last_name}'
    

class BookAuthor(models.Model):
    book=models.ForeignKey(Book,on_delete=models.CASCADE)
    author=models.ForeignKey(Author,on_delete=models.CASCADE)

    class Meta:
        db_table = 'book_author'

    def __str__(self):
        return f'{self.book.title} by {self.author.first_name} {self.author.last_name}'
    
class Review(models.Model):
    comment=models.CharField(max_length=100)
    rating=models.IntegerField(
        default=0,
        validators=[
            MaxValueValidator(5),
            MinValueValidator(0)
        ]
    )
    book=models.ForeignKey(Book,on_delete=models.CASCADE)
    user=models.ForeignKey(CustomUser,on_delete=models.CASCADE)

    class Meta:
        db_table ='review'

    def __str__(self):
        return f'{self.rating} - {self.book.title} review by {self.user.username}'

users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
# Create your models here.

class CustomUser(AbstractUser):
    image=models.ImageField(upload_to='users_images/',blank=True,null=True,default='default_images/user_image.png')
    
    class Meta:
        db_table = 'customuser'

    def __self__(self):
        return self.username

users/forms.py
from django import forms
from users.models import CustomUser

class CustomUserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)

    class Meta:
        model = CustomUser
        fields = ('username', 'email', 'first_name', 'last_name', 'image', 'password')

    def save(self, commit=True):
        user = super().save(commit=False)  # Don't commit yet to avoid saving twice
        user.set_password(self.cleaned_data["password"])
        if commit:
            user.save()
        return user
    
        

home/views.py
from django.shortcuts import render
from django.views import View
from django.contrib.auth.mixins import LoginRequiredMixin
# Create your views here.

def landing_page(request):
    return render(request, 'landing_page.html')

class GetTest(LoginRequiredMixin,View):
    def get(self,request):
        if request.user.is_authenticated():    
            return render(request, 'get_test.html')
        else:
            return render(request, 'users:login')

products/views.py
from django.views.generic import ListView, DetailView, UpdateView,CreateView,   DeleteView
from django.shortcuts import render
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views import View
from .models import Book
from django.urls import reverse_lazy
# Create your views here.

# class ListView(View):
#     def get(self,request):
#         book=Book.objects.all().order_by('-pk')
#         return render(request, 'book/book_list.html',{'book':book})

class BookListView(ListView):
    model = Book
    template_name = 'book/book_list.html'
    context_object_name = 'book'

class BookDetailView(DetailView):
    model = Book
    template_name = 'book/book_detail.html'


class BookCreateView(CreateView):
    model = Book
    template_name = 'book/book_create.html'
    fields = '__all__'
    success_url = reverse_lazy('products:book_list')

class BookDeleteView(DeleteView):
    model = Book
    template_name = 'book/book_detail.html'
    success_url = reverse_lazy('products:book_list')

users/views.py
from django.shortcuts import render,redirect
from .models import CustomUser
from django.views import View
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import login,logout
from django.contrib.auth.mixins import LoginRequiredMixin
from .forms import CustomUserForm
# Create your views here.

class RegisterView(View):
    def get(self, request):
        create_form = CustomUserForm()
        context = {
            'form': create_form
        }
        return render(request, 'register.html', context=context)

    def post(self, request):
        create_form = CustomUserForm(data=request.POST, files=request.FILES)
        if create_form.is_valid():
            create_form.save()
            return redirect('users:login')
        else:
            context = {
                'form': create_form
            }
            return render(request, 'register.html', context=context)


# class RegisterView(View):
#     def get(self, request):
#         return render(request, 'register.html')
#
#     def post(self, request):
#         username = request.POST['username']
#         password = request.POST['password']
#         email = request.POST['email']
#         last_name = request.POST['last_name']
#         first_name = request.POST['first_name']
#
#         user = CustomUser.objects.create_user(
#             username=username,
#             email=email,
#             first_name=first_name,
#             last_name=last_name
#         )
#         user.set_password(password)
#         user.save()
#
#         return redirect('users:login')


class LoginView(View):
    def get(self, request):
        login_form = AuthenticationForm()
        context = {
            'form': login_form
        }
        return render(request, 'login.html', context=context)

    def post(self, request):
        login_form = AuthenticationForm(data=request.POST)
        if login_form.is_valid():
            user = login_form.get_user()
            login(request, user)
            return redirect('landing_page')
        else:
            context = {
                'form': login_form
            }
            return render(request, 'login.html', context=context)


class LogoutView(LoginRequiredMixin, View):
    def get(self, request):
        logout(request)
        return redirect('landing_page')

templates/book/book_create.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Create Book</title>
</head>
<body>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Create Book</button>
    </form>
</body>
</html>

templates/book/book_detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{ object.title }}</title>
</head>
<body>
    <h1>{{ object.title }}</h1>   
    <img src="{{ object.image.url }}" alt="itss">
    <h4>Description: {{object.description}}</h4>
    <h4>Price: {{object.price}}</h4>
    <h4>Page: {{object.page}}</h4> 

    <button>
        <a href="{% url 'products:book_delete' object.pk %}">Delete </a>
    </button>
</body>
</html>

templates/book/book_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Book</title>
</head>
<body>
    <h1>Book Page</h1>
    {% for b in book %}
        <a href="{% url  'products:book_detail' b.pk %}"> {{ b.title}}</a><br><br>
    {% endfor %}
    <button> 
        <a href="{% url 'products:book_create' %}">Create Book</a>
    </button>
</body>
</html>

templates/get_text.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    
</body>
</html>

templates/landing_page.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Home_page</title>
</head>
<body>
    <h1>Home page</h1>
    <a href="{% url 'products:book_list' %}">Books</a> /
    <a href="{% url 'users:register' %}">Register</a> /
    <!-- <a href="{% url 'home:test' %}">Test</a> / -->
    {% if request.user.is_authenticated %}
        <a href="{% url 'users:logout' %}">Logout</a>
    {% else %}
        <a href="{% url 'users:login' %}">Login</a>
    {% endif %}
</body>
</html>

users/templates/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Login page</title>
</head>
<body>
    <h1>Login Page</h1>
    <form method="post">
        {% csrf_token %}
        {{form.as_p}}
        <button type="submit" >Submit</button>
    </form>
</body>
</html>

users/templates/register.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Register page</title>
</head>
<body>
    <h1>Registe page</h1>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" >Submit</button>
    </form>
</body>
</html>